# Metadata
reference:
    abundant_rna_file: data/00ref/abundant_rna.fasta
    ensembl_ver: 38
    ensembl_gtf: data/00ref/hg38.ensGene.gtf
    genome_build: hg38
    genome_file: data/00ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna 
    genome_source: ucsd
remove_duplicated_reads: true
star_db:
    star_index: data/00ref
    sjdbOverhang: 49 
samples:
    AK9197-1_S1_L001: # Example prefix entry for fastq file AK9197-1_S1_L001_R1.fastq.gz and AK9197-1_S1_L001_R2.fastq.gz 
